import Link from "next/link";

export default function HomePage() {
  return (
    <main className="mx-auto max-w-5xl px-6 py-16">
      <header className="mb-12">
        <h1 className="text-4xl font-semibold tracking-tight text-zinc-100">
          Event / Macro Studier
        </h1>
        <p className="mt-3 text-zinc-400">
          Investment research workspace. Seed macro & geopolitical events, build a knowledge
          graph of market actors, simulate reactions, generate scenario reports.
        </p>
      </header>

      <section className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <Card
          href="/events"
          title="Events"
          description="Seed macro/geopolitical events and inspect the knowledge graph generated for each."
        />
        <Card
          href="/brain"
          title="Second Brain"
          description="Ingest news, docs, market data. Semantic retrieval over your private corpus."
        />
        <Card
          href="/markets"
          title="Markets"
          description="Quotes, time-series and news feeds from Yahoo Finance and curated RSS sources."
        />
        <Card
          href="/reports"
          title="Reports"
          description="Scenario reports generated by the multi-actor simulation pipeline."
        />
      </section>

      <footer className="mt-16 text-xs text-zinc-500">
        Sprint 1 — Event Studier foundations. Built on Next.js · Supabase · Anthropic ·
        Inngest.
      </footer>
    </main>
  );
}

function Card({ href, title, description }: { href: string; title: string; description: string }) {
  return (
    <Link
      href={href}
      className="rounded-lg border border-border bg-panel p-5 transition hover:border-accent/40"
    >
      <h2 className="text-lg font-medium text-zinc-100">{title}</h2>
      <p className="mt-2 text-sm text-zinc-400">{description}</p>
    </Link>
  );
}
